version: "3.4"

services:
  authenticator:
    build:
      context: ./
    ports:
      - "3000:80"
    container_name: authenticator
    restart: always
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx-certbot
      args:
        DOMAIN: domain.com
    environment:
      CERTBOT_EMAIL: email@example.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certs:/etc/letsencrypt
